name: "assign reviewers"

on: pull_request

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Assign Reviewers
        uses: ohnogumi/auto-reviewers@v0.0.1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
